export const SKILLS = [
  { 
    name: "Navigation", 
    tier: 1,
    cost: 8, 
    prereqs: [], 
    appearance: <></>,
    unlocks: [
      {
        name: "Movement",
        description: "Allows troops to travel on all terrain.",
        appearance: <></>
      },
    ], 
  },
  { 
    name: "Fishing", 
    tier: 2,
    cost: 8, 
    prereqs: ["Navigation"], 
    appearance: <></>,
    unlocks: [
      {
        name: "Port",
        description: "Used to convert land units to boats.",
        appearance: <></>
      },
      {
        name: "Fishing Net",
        description: "Unlocks the Fishing Net, which can be placed on Water and Ocean tiles to collect resources the following turn.",
        appearance: <></>
      },
    ], 
  },
  { 
    name: "Seafaring", 
    tier: 3,
    cost: 8, 
    prereqs: ["Fishing"],
    appearance: <></>,
    unlocks: [
      {
        name: "Advanced Nets",
        description: "Nets now have a 20% chance of catching rare items.",
        appearance: <></>
      },
      {
        name: "Warship",
        description: "Unlocks the Warship troop.",
        appearance: <></>
      },
    ],
  },
  { 
    name: "Aquatism", 
    tier: 4,
    cost: 8, 
    prereqs: ["Seafaring"],
    appearance: <></>,
    unlocks: [
      {
        name: "Leviathan",
        description: "Unlocks the Leviathan troop.",
        appearance: <></>
      },
      {
        name: "Stats Bonus",
        description: "Naval units gain +20% attack damage and +20% defense.",
        appearance: <></>
      },
      {
        name: "Hazard Immunity",
        description: "Naval units are now immune to water hazards, such as whirlpools and storms.",
        appearance: <></>
      },
    ],
  },
  { 
    name: "Roads", 
    tier: 2,
    cost: 8, 
    prereqs: ["Navigation"],
    appearance: <></>,
    unlocks: [
      {
        name: "Roads",
        description: "Can be used for faster navigation.",
        appearance: <></>
      },
      {
        name: "Bridges",
        description: "Allows land units to travel over water.",
        appearance: <></>
      },
    ],
  },
  { 
    name: "Surveying", 
    tier: 3,
    cost: 8, 
    prereqs: ["Roads"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Cartographer", 
    tier: 4,
    cost: 8, 
    prereqs: ["Surveying"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Toolmaking", 
    tier: 1,
    cost: 8, 
    prereqs: [],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Prospecting", 
    tier: 2,
    cost: 8, 
    prereqs: ["Toolmaking"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Metallurgy", 
    tier: 3,
    cost: 8, 
    prereqs: ["Prospecting"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Master Miner", 
    tier: 4,
    cost: 8, 
    prereqs: ["Metallurgy"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Melee Training", 
    tier: 2,
    cost: 8, 
    prereqs: ["Toolmaking"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Tactics", 
    tier: 3,
    cost: 8, 
    prereqs: ["Melee Training"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Elite Warriors", 
    tier: 4,
    cost: 8, 
    prereqs: ["Tactics"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Domestication", 
    tier: 1,
    cost: 8, 
    prereqs: [],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Farming", 
    tier: 2,
    cost: 8, 
    prereqs: ["Domestication"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Industry", 
    tier: 3,
    cost: 8, 
    prereqs: ["Farming"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Agro-mastery", 
    tier: 4,
    cost: 8, 
    prereqs: ["Industry"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Pets", 
    tier: 2,
    cost: 8, 
    prereqs: ["Domestication"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Animal Training", 
    tier: 3,
    cost: 8, 
    prereqs: ["Pets"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Beast Mastery", 
    tier: 4,
    cost: 8, 
    prereqs: ["Animal Training"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Herbalism", 
    tier: 1,
    cost: 8, 
    prereqs: [],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "First Aid", 
    tier: 2,
    cost: 8, 
    prereqs: ["Herbalism"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Surgery", 
    tier: 3,
    cost: 8, 
    prereqs: ["First Aid"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Healing", 
    tier: 4,
    cost: 8, 
    prereqs: ["Surgery"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Potions", 
    tier: 2,
    cost: 8, 
    prereqs: ["Herbalism"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Elixirs", 
    tier: 3,
    cost: 8, 
    prereqs: ["Potions"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Alchemy", 
    tier: 4,
    cost: 8, 
    prereqs: ["Elixirs"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Knowledge", 
    tier: 1,
    cost: 8, 
    prereqs: [],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Spellcasting", 
    tier: 2,
    cost: 8, 
    prereqs: ["Knowledge"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Enchanting", 
    tier: 3,
    cost: 8, 
    prereqs: ["Spellcasting"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Mystic Arts", 
    tier: 4,
    cost: 8, 
    prereqs: ["Enchanting"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Logic", 
    tier: 2,
    cost: 8, 
    prereqs: ["Knowledge"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Science", 
    tier: 3,
    cost: 8, 
    prereqs: ["Logic"],
    appearance: <></>,
    unlocks: [],
  },
  { 
    name: "Sage", 
    tier: 4,
    cost: 8, 
    prereqs: ["Science"],
    appearance: <></>,
    unlocks: [],
  },
];
